name: Trigger Velocitas Upgrade Workflow

on:
  release:
    types: [published]

env:
  CHECK_UPDATES_FILE: check-updates.yml

jobs:
  trigger:
    strategy:
      matrix:
        repo: ["template-test"]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Workflow
        run: |
          echo "${{ secrets.GH_CLI_PAT }}" | gh auth login --with-token
          gh workflow run $CHECK_UPDATES_FILE -R dennismeister93/${{ matrix.repo }}
